//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetWebAPI.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DriverManagementEntities : DbContext
    {
        public DriverManagementEntities()
            : base("name=DriverManagementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ActivityTable> ActivityTable { get; set; }
        public virtual DbSet<AdminDetail> AdminDetail { get; set; }
        public virtual DbSet<DriverTable> DriverTable { get; set; }
        public virtual DbSet<GenderTable> GenderTable { get; set; }
        public virtual DbSet<HobbyTable> HobbyTable { get; set; }
        public virtual DbSet<MapDocAdmin> MapDocAdmin { get; set; }
        public virtual DbSet<MapDriverHob> MapDriverHob { get; set; }
        public virtual DbSet<MapImgDriver> MapImgDriver { get; set; }
    }
}
