//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HobbyTable
    {
        public int HobbyId { get; set; }
        public string Hobby { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
