//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NetWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MapImgDriver
    {
        public int ImageId { get; set; }
        public Nullable<int> DriverId { get; set; }
        public string Filepath { get; set; }
        public string Filename { get; set; }
    }
}
